:root {
    --primary:#1d4ed8; --primary-dark:#1e40af; --primary-soft:#eff6ff;
    --success:#15803d; --success-soft:#f0fdf4; --warning:#b45309; --warning-soft:#fffbeb;
    --danger:#b91c1c; --danger-soft:#fef2f2; --text:#172033; --muted:#667085;
    --border:#e4e7ec; --surface:#fff; --background:#f5f7fb;
}
*{box-sizing:border-box} body{margin:0;font-family:Arial,Helvetica,sans-serif;background:var(--background);color:var(--text)}
button,input,select,textarea,a{font:inherit}.header{background:linear-gradient(135deg,#1d4ed8,#2563eb);color:#fff;padding:22px 32px;box-shadow:0 8px 24px rgba(29,78,216,.16)}
.header-inner,.container{width:min(1380px,100%);margin:0 auto}.header-inner{display:flex;justify-content:space-between;align-items:center;gap:20px}.brand h1{margin:0;font-size:25px}.brand p{margin:6px 0 0;font-size:13px;opacity:.9}.container{padding:28px 30px 42px}
.topbar{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:18px}.page-title h2{margin:0 0 7px;font-size:24px}.page-title p{margin:0;color:var(--muted);font-size:14px;line-height:1.5}.actions{display:flex;gap:9px;flex-wrap:wrap}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:38px;padding:9px 13px;border-radius:8px;border:1px solid transparent;text-decoration:none;cursor:pointer;font-size:13px;font-weight:700;transition:.18s ease;white-space:nowrap}.btn:hover{transform:translateY(-1px)}.btn-primary{background:var(--primary);color:#fff}.btn-primary:hover{background:var(--primary-dark)}.btn-secondary{background:#fff;color:#344054;border-color:#d0d5dd}.btn-secondary:hover{background:#f9fafb}.btn-success{background:var(--success);color:#fff}
.alert{padding:13px 15px;margin-bottom:16px;border-radius:9px;font-size:14px;line-height:1.5}.alert-success{background:var(--success-soft);color:#166534;border:1px solid #bbf7d0}.alert-error{background:var(--danger-soft);color:#991b1b;border:1px solid #fecaca}.alert-warning{background:var(--warning-soft);color:#92400e;border:1px solid #fde68a}
.stats-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-bottom:18px}.stats-grid.four{grid-template-columns:repeat(4,minmax(0,1fr))}.stat-card{background:#fff;border:1px solid var(--border);border-radius:11px;padding:16px 17px;box-shadow:0 2px 8px rgba(16,24,40,.035)}.stat-label{color:var(--muted);font-size:12px;font-weight:700}.stat-value{margin-top:7px;font-size:22px;font-weight:800}.stat-note{margin-top:5px;font-size:12px;color:var(--muted)}
.card{background:#fff;border:1px solid var(--border);border-radius:12px;box-shadow:0 3px 12px rgba(16,24,40,.04)}.filter-card{padding:17px;margin-bottom:16px}.filter-grid{display:grid;grid-template-columns:minmax(220px,1.6fr) repeat(2,minmax(150px,.8fr)) auto;gap:10px;align-items:end}.filter-grid.with-select{grid-template-columns:minmax(210px,1.4fr) minmax(180px,.9fr) repeat(2,minmax(145px,.7fr)) auto}.field label{display:block;margin-bottom:6px;color:#475467;font-size:12px;font-weight:700}.field input,.field select,.field textarea{width:100%;border:1px solid #d0d5dd;border-radius:8px;padding:10px 11px;background:#fff;color:var(--text);outline:none}.field input,.field select{height:40px}.field textarea{min-height:100px;resize:vertical}.field input:focus,.field select:focus,.field textarea:focus{border-color:#84adff;box-shadow:0 0 0 3px rgba(37,99,235,.09)}.field .readonly{background:#f8fafc;color:#475467}.filter-buttons{display:flex;gap:7px}
.table-card{overflow:hidden}.table-meta{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:14px 16px;border-bottom:1px solid var(--border)}.table-meta strong{font-size:14px}.table-meta span{color:var(--muted);font-size:12px}.table-wrapper{overflow-x:auto}table.data{width:100%;border-collapse:collapse;min-width:1040px}table.data thead th{background:#f8fafc;color:#475467;padding:12px 11px;border-bottom:1px solid var(--border);text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.35px;white-space:nowrap}table.data tbody td{padding:13px 11px;border-bottom:1px solid #eef0f3;font-size:13px;vertical-align:middle}table.data tbody tr:last-child td{border-bottom:none}table.data tbody tr:hover{background:#fbfcfe}.center{text-align:center}.right{text-align:right}.nowrap{white-space:nowrap}.strong{font-weight:700}.muted{color:var(--muted)}
.badge{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:999px;font-size:11px;font-weight:800;white-space:nowrap}.badge-success{color:#166534;background:#dcfce7}.badge-warning{color:#92400e;background:#fef3c7}.badge-danger{color:#991b1b;background:#fee2e2}.badge-muted{color:#475467;background:#f2f4f7}.badge-blue{color:#1d4ed8;background:#eff6ff}.row-actions{display:flex;flex-wrap:wrap;gap:6px}.action-link{display:inline-flex;align-items:center;justify-content:center;min-height:30px;padding:6px 9px;border-radius:7px;border:1px solid #d0d5dd;background:#fff;color:#344054;text-decoration:none;font-size:11px;font-weight:800}.action-link:hover{background:#f8fafc}.action-link.done{color:#166534;border-color:#bbf7d0;background:#f0fdf4}.action-link.create{color:#1d4ed8;border-color:#bfdbfe;background:#eff6ff}
.empty-state{padding:48px 20px!important;text-align:center;color:var(--muted)}.empty-title{color:#344054;font-weight:800;margin-bottom:6px}.pagination-wrap{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:14px 16px;border-top:1px solid var(--border)}.pagination-info{color:var(--muted);font-size:12px}.pagination{display:flex;gap:5px;flex-wrap:wrap}.page-link{min-width:34px;height:34px;display:inline-flex;align-items:center;justify-content:center;padding:0 9px;border:1px solid #d0d5dd;border-radius:7px;text-decoration:none;color:#344054;background:#fff;font-size:12px;font-weight:700}.page-link.active{background:var(--primary);border-color:var(--primary);color:#fff}.page-link.disabled{color:#98a2b3;background:#f9fafb;pointer-events:none}
.form-layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,.8fr);gap:18px}.form-card{padding:22px}.form-card h3,.summary-card h3{margin:0 0 18px;font-size:16px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.form-grid .full{grid-column:1/-1}.summary-card{padding:20px;align-self:start}.summary-list{display:grid;gap:13px}.summary-item{padding-bottom:12px;border-bottom:1px solid #eef0f3}.summary-item:last-child{border-bottom:none;padding-bottom:0}.summary-label{font-size:11px;text-transform:uppercase;letter-spacing:.35px;color:var(--muted);font-weight:800}.summary-value{margin-top:5px;font-size:14px;font-weight:700;line-height:1.5}.summary-total{margin-top:16px;padding:14px;border-radius:9px;background:var(--primary-soft);color:#1e40af}.summary-total .summary-value{font-size:20px}.form-footer{display:flex;gap:9px;flex-wrap:wrap;margin-top:20px;padding-top:18px;border-top:1px solid var(--border)}.help{margin-top:6px;color:var(--muted);font-size:12px;line-height:1.45}.error-text{margin-top:6px;color:#b91c1c;font-size:12px}
@media(max-width:900px){.stats-grid,.stats-grid.four{grid-template-columns:repeat(2,minmax(0,1fr))}.filter-grid,.filter-grid.with-select{grid-template-columns:1fr 1fr}.filter-buttons{grid-column:1/-1}.form-layout{grid-template-columns:1fr}.header{padding:20px}.container{padding:22px 16px 34px}.topbar{align-items:flex-start;flex-direction:column}}
@media(max-width:600px){.header-inner{align-items:flex-start;flex-direction:column}.topbar{margin-bottom:16px}.stats-grid,.stats-grid.four{grid-template-columns:1fr}.filter-grid,.filter-grid.with-select,.form-grid{grid-template-columns:1fr}.filter-buttons{grid-column:auto}.actions{width:100%}.actions .btn{flex:1}.pagination-wrap{align-items:flex-start;flex-direction:column}.page-title h2{font-size:21px}}
