:root {
    --primary:#1d4ed8; --primary-dark:#1e40af; --primary-soft:#eff6ff;
    --success:#15803d; --success-soft:#f0fdf4; --warning:#b45309; --warning-soft:#fffbeb;
    --danger:#b91c1c; --danger-soft:#fef2f2; --text:#172033; --muted:#667085;
    --border:#e4e7ec; --surface:#fff; --background:#f5f7fb;
}
*{box-sizing:border-box} body{margin:0;font-family:Arial,Helvetica,sans-serif;background:var(--background);color:var(--text)}
button,input,textarea,a{font:inherit}.school-header{background:linear-gradient(135deg,#1d4ed8,#2563eb);color:#fff;padding:24px 32px;box-shadow:0 8px 24px rgba(29,78,216,.16)}
.school-header-inner,.school-container{width:min(1120px,100%);margin:0 auto}.school-header-inner{display:flex;justify-content:space-between;align-items:center;gap:20px}.school-header h1{margin:0;font-size:25px;letter-spacing:-.3px}.school-header p{margin:6px 0 0;font-size:13px;opacity:.9;line-height:1.5}.school-container{padding:28px 24px 44px}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:40px;padding:9px 14px;border:1px solid transparent;border-radius:8px;text-decoration:none;font-size:13px;font-weight:800;cursor:pointer;transition:.16s ease}.btn:hover{transform:translateY(-1px)}.btn-primary{background:var(--primary);color:#fff}.btn-primary:hover{background:var(--primary-dark)}.btn-secondary{background:#fff;color:#344054;border-color:#d0d5dd}.btn-secondary:hover{background:#f9fafb}.btn-danger{background:#fff;color:#b91c1c;border-color:#fecaca}
.alert{padding:13px 15px;margin-bottom:17px;border-radius:9px;font-size:13px;line-height:1.5}.alert-success{background:var(--success-soft);color:#166534;border:1px solid #bbf7d0}.alert-error{background:var(--danger-soft);color:#991b1b;border:1px solid #fecaca}.alert-warning{background:var(--warning-soft);color:#92400e;border:1px solid #fde68a}.alert ul{margin:7px 0 0;padding-left:18px}
.profile-hero{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:18px;padding:22px;background:#fff;border:1px solid var(--border);border-radius:14px;box-shadow:0 3px 12px rgba(16,24,40,.04)}.school-avatar{width:64px;height:64px;border-radius:16px;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#dbeafe,#eff6ff);border:1px solid #bfdbfe;color:#1d4ed8;font-size:22px;font-weight:900}.profile-hero h2{margin:0 0 6px;font-size:22px}.profile-hero p{margin:0;color:var(--muted);font-size:13px;line-height:1.5}.profile-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
.completeness{margin-top:14px;display:flex;align-items:center;gap:10px}.progress{height:8px;flex:1;max-width:260px;background:#eef2f6;border-radius:999px;overflow:hidden}.progress span{display:block;height:100%;background:#22c55e;border-radius:999px}.progress-text{font-size:11px;color:#667085;font-weight:700}
.info-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:18px}.info-card{padding:18px;background:#fff;border:1px solid var(--border);border-radius:12px;box-shadow:0 2px 8px rgba(16,24,40,.035)}.info-label{font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:#98a2b3;font-weight:800}.info-value{margin-top:7px;color:#344054;font-size:15px;font-weight:800;line-height:1.45}.info-sub{margin-top:5px;color:#667085;font-size:12px;line-height:1.45}.address-card{margin-top:14px;padding:19px;background:#fff;border:1px solid var(--border);border-radius:12px}.address-card h3{margin:0 0 8px;font-size:14px}.address-card p{margin:0;color:#475467;line-height:1.65;font-size:13px}.section-note{margin-top:18px;padding:16px 17px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:11px;color:#1e40af;font-size:13px;line-height:1.6}.section-note strong{display:block;margin-bottom:3px}
.breadcrumb{margin-bottom:14px;color:#667085;font-size:12px}.breadcrumb a{color:#1d4ed8;text-decoration:none;font-weight:800}.form-card{background:#fff;border:1px solid var(--border);border-radius:14px;box-shadow:0 3px 14px rgba(16,24,40,.05);overflow:hidden}.form-card-head{padding:20px 22px;border-bottom:1px solid var(--border)}.form-card-head h2{margin:0 0 6px;font-size:20px}.form-card-head p{margin:0;color:#667085;font-size:13px;line-height:1.55}.school-form{padding:22px}.form-section{margin-bottom:22px}.form-section:last-of-type{margin-bottom:0}.form-section-title{display:flex;align-items:center;gap:9px;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid #eef0f3}.form-section-icon{width:28px;height:28px;border-radius:8px;display:flex;align-items:center;justify-content:center;background:#eff6ff;color:#1d4ed8;font-size:12px;font-weight:900}.form-section-title h3{margin:0;font-size:14px}.form-section-title span{margin-left:auto;color:#98a2b3;font-size:11px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px 18px}.field.full{grid-column:1/-1}.field label{display:block;margin-bottom:7px;color:#344054;font-size:12px;font-weight:800}.field label em{color:#dc2626;font-style:normal}.field input,.field textarea{width:100%;border:1px solid #d0d5dd;border-radius:8px;padding:10px 11px;background:#fff;color:#172033;outline:none}.field input{height:42px}.field textarea{min-height:92px;resize:vertical;line-height:1.5}.field input:focus,.field textarea:focus{border-color:#84adff;box-shadow:0 0 0 3px rgba(37,99,235,.09)}.field-help{margin-top:6px;color:#98a2b3;font-size:11px;line-height:1.45}.field-error{margin-top:6px;color:#b91c1c;font-size:11px;font-weight:700}.form-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:24px;padding-top:18px;border-top:1px solid var(--border)}
@media(max-width:800px){.school-header{padding:20px}.school-header-inner{align-items:flex-start;flex-direction:column}.school-container{padding:22px 16px 36px}.profile-hero{grid-template-columns:auto 1fr}.profile-actions{grid-column:1/-1;justify-content:flex-start}.info-grid{grid-template-columns:1fr 1fr}.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}}
@media(max-width:540px){.school-header h1{font-size:22px}.profile-hero{grid-template-columns:1fr}.school-avatar{width:54px;height:54px}.info-grid{grid-template-columns:1fr}.profile-actions,.form-actions{flex-direction:column}.profile-actions .btn,.form-actions .btn{width:100%}.school-form,.form-card-head{padding:17px}}
